import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script type='text/javascript'>
        
      </script>

      <main className={styles.main}>
       <p>edit page</p>
       <div id="root">wait...</div>
       
       
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
